name: blackbox
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  flutter_local_notifications: ^3.0.2
  provider: ^4.3.2+2
  #provider 4.3.2+2 is the latest 2020-11-01
  google_api_availability: ^2.0.4
  rflutter_alert: ^1.0.3
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  wakelock: ^0.5.2
  #  flutter_linkify: ^5.0.0  #Wrong app and version, used 4.0.2 in MyGiggz

  #  Worked before upgrade:
  #  firebase_core: ^0.5.1
  #  firebase_auth: ^0.18.2
  #  cloud_firestore: ^0.14.2

  #  Works except for Cloud Messaging:
  #  firebase_core: ^0.5.3
  #  firebase_auth: ^0.18.4
  #  cloud_firestore: ^0.14.4
  #  firebase_messaging: ^7.0.3

  #  Way earlier version:
  #  firebase_core: ^0.4.4
  #  firebase_auth: ^0.16.1  #Only accepts firebase_core ^0.4.4
  #  cloud_firestore: ^0.13.0-dev.1
  #  firebase_messaging: ^8.0.0-dev.8

  #  From MyGiggz after messaging upgrade:
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_messaging: ^8.0.0-dev.14 #From Github answer

  http: ^0.12.2
  firebase_admin: ^0.1.4

#------------------------------------------------------------------------------------------------
#  Doesn't work:
#  //add in dependencies
#  androidx.multidex:multidex: 2.0.1

#dependency_overrides:
#  firebase_messaging_platform_interface:
#    git:
#      url: https://github.com/FirebaseExtended/flutterfire
#      path: packages/firebase_messaging/firebase_messaging_platform_interface
#      ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71
#------------------------------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/beams/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
