name: blackbox
description: Flutter board game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  flutter_local_notifications: ^3.0.2
  provider: ^4.3.2+2
  #provider 4.3.2+2 is the latest 2020-11-01
  google_api_availability: ^2.0.4
  rflutter_alert: ^1.0.3
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  #  flutter_linkify: ^5.0.0  #Wrong app and version, used 4.0.2 in MyGiggz

  #  Worked before upgrade:
  #  firebase_core: ^0.5.1
  #  firebase_auth: ^0.18.2
  #  cloud_firestore: ^0.14.2

  #  Works except for Cloud Messaging:
  #  firebase_core: ^0.5.3
  #  firebase_auth: ^0.18.4
  #  cloud_firestore: ^0.14.4
  #  firebase_messaging: ^7.0.3

  #  Way earlier version:
  #  firebase_core: ^0.4.4
  #  firebase_auth: ^0.16.1  #Only accepts firebase_core ^0.4.4
  #  cloud_firestore: ^0.13.0-dev.1
  #  firebase_messaging: ^8.0.0-dev.8

  #  From MyGiggz after messaging upgrade:
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_messaging: ^8.0.0-dev.14 #From Github answer

  http: ^0.12.2
  firebase_admin: ^0.1.4

#  Doesn't work:
#  //add in dependencies
#  androidx.multidex:multidex: 2.0.1

#dependency_overrides:
#  firebase_messaging_platform_interface:
#    git:
#      url: https://github.com/FirebaseExtended/flutterfire
#      path: packages/firebase_messaging/firebase_messaging_platform_interface
#      ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#name: blackbox
#description: A new Flutter project.
#
## The following line prevents the package from being accidentally published to
## pub.dev using `pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
## The following defines the version and build number for your application.
## A version number is three numbers separated by dots, like 1.2.43
## followed by an optional build number separated by a +.
## Both the version and the builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
## In Android, build-name is used as versionName while build-number used as versionCode.
## Read more about Android versioning at https://developer.android.com/studio/publish/versioning
## In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
## Read more about iOS versioning at
## https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
#
#environment:
#  sdk: ">=2.7.0 <3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#
#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.2
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
## For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#
## The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#
#  # To add assets to your application, add an assets section, like this:
#  # assets:
#  #   - images/a_dot_burr.jpeg
#  #   - images/a_dot_ham.jpeg
#
#  # An image asset can refer to one or more resolution-specific "variants", see
#  # https://flutter.dev/assets-and-images/#resolution-aware.
#
#  # For details regarding adding assets from package dependencies, see
#  # https://flutter.dev/assets-and-images/#from-packages
#
#  # To add custom fonts to your application, add a fonts section here,
#  # in this "flutter" section. Each entry in this list should have a
#  # "family" key with the font family name, and a "fonts" key with a
#  # list giving the asset and other descriptors for the font. For
#  # example:
#  # fonts:
#  #   - family: Schyler
#  #     fonts:
#  #       - asset: fonts/Schyler-Regular.ttf
#  #       - asset: fonts/Schyler-Italic.ttf
#  #         style: italic
#  #   - family: Trajan Pro
#  #     fonts:
#  #       - asset: fonts/TrajanPro.ttf
#  #       - asset: fonts/TrajanPro_Bold.ttf
#  #         weight: 700
#  #
#  # For details regarding fonts from package dependencies,
#  # see https://flutter.dev/custom-fonts/#from-packages
