# This project can't auto-import Flutter packages BUT...
# has full access to project files, even if they are not
# in the same sub folder
name: blackbox
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2

environment:
#  sdk: '>=2.12.0 <3.0.0'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.4.0
  #  modal_progress_hud: ^0.1.3
  provider: ^6.0.2
  #provider 4.3.2+2 is the latest 2020-11-01
  google_api_availability: ^5.0.0
  rflutter_alert: ^2.0.4
  cupertino_icons: ^1.0.4
  wakelock: ^0.6.1+2
  #  flutter_linkify: ^5.0.0  #Wrong app and version, used 4.0.2 in MyGiggz
  navigation_history_observer: ^1.1.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.2
  pretty_json: ^2.0.0

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_messaging: ^14.6.4
  #  firebase_admin: ^0.1.4

  intl: ^0.18.1
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/beams/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#..............................................................................
# Before flutter upgrade that would allegedly erase local changes:
#
#name: blackbox
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#version: 1.0.2
#
#environment:
#  #  sdk: '>=2.12.0 <3.0.0'
#  sdk: '>=2.17.0 <3.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#  modal_progress_hud_nsn: ^0.4.0
#  #  modal_progress_hud: ^0.1.3
#  provider: ^6.0.2
#  #provider 4.3.2+2 is the latest 2020-11-01
#  google_api_availability: ^5.0.0
#  rflutter_alert: ^2.0.4
#  cupertino_icons: ^1.0.4
#  wakelock: ^0.6.1+2
#  #  flutter_linkify: ^5.0.0  #Wrong app and version, used 4.0.2 in MyGiggz
#  navigation_history_observer: ^1.1.0
#  flutter_linkify: ^6.0.0
#  url_launcher: ^6.1.2
#  pretty_json: ^2.0.0
#
#  firebase_core: ^2.14.0
#  firebase_auth: ^4.6.3
#  cloud_firestore: ^4.8.2
#  firebase_messaging: ^14.6.4
#  #  firebase_admin: ^0.1.4
#
#  intl: ^0.18.1
#  http: ^1.1.0
#  flutter_local_notifications: ^15.1.0+1
#
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_native_splash: ^2.3.1
#
#flutter:
#  uses-material-design: true
#
#  assets:
#    - images/
#    - images/beams/
#
#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: fonts/Pacifico-Regular.ttf
#
#    - family: Source Sans Pro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf
#  #   - family: Trajan Pro
#  #     fonts:
#  #       - asset: fonts/TrajanPro.ttf
#  #       - asset: fonts/TrajanPro_Bold.ttf
#  #         weight: 700
#  #
#  # For details regarding fonts from package dependencies,
#  # see https://flutter.dev/custom-fonts/#from-packages
